/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ./counterTMR.sv                                                                        *
 *                                                                                                  *
 * user    : michaero                                                                               *
 * host    : camellia.ee.ethz.ch                                                                    *
 * date    : 08/08/2025 19:23:44                                                                    *
 *                                                                                                  *
 * workdir : /scratch/michaero/git/croc/working_dir/obi_peripherals/tmrg_files                      *
 * cmd     : /home/michaero/.local/bin/tmrg --inc-                                                  *
 *           dir=.bender/git/checkouts/common_cells-3510fb294b1f35a1/include ../tmrg_src/sync.sv    *
 *           ../tmrg_src/delta_counter.sv ../tmrg_src/counter.sv ../tmrg_src/fifo_v3.sv             *
 *           ../hw/obi_uart/obi_uart_pkg.sv ../hw/obi_uart/obi_uart_baudgen.sv                      *
 *           ../hw/obi_uart/obi_uart_interrupts.sv ../hw/obi_uart/obi_uart_modem.sv                 *
 *           ../hw/obi_uart/obi_uart_rx.sv ../hw/obi_uart/obi_uart_tx.sv                            *
 *           ../hw/obi_uart/obi_uart_register.sv ../hw/obi_uart/obi_uart.sv --top-module=delta_counter *
 * tmrg rev: 7e2935137fada05d9957c7acbad06f9f466f5f7e                                               *
 *                                                                                                  *
 * src file: ../tmrg_src/counter.sv                                                                 *
 *           Git SHA           : e6e399eed41c083c058e93c183edcf840d8a1f2a (?? ../tmrg_src/counter.sv) *
 *           Modification time : 2025-08-08 18:55:06.114267                                         *
 *           File Size         : 1728                                                               *
 *           MD5 hash          : 65d0c522ef2de224c1636add09736233                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module counterTMR #(
  parameter int unsigned WIDTH = 4,
  parameter bit STICKY_OVERFLOW = 1'b0
) (
  input logic clk_i,
  input logic rst_ni,
  input logic clear_iA,
  input logic clear_iB,
  input logic clear_iC,
  input logic en_iA,
  input logic en_iB,
  input logic en_iC,
  input logic load_iA,
  input logic load_iB,
  input logic load_iC,
  input logic down_iA,
  input logic down_iB,
  input logic down_iC,
  input logic [WIDTH - 1:0] d_iA,
  input logic [WIDTH - 1:0] d_iB,
  input logic [WIDTH - 1:0] d_iC,
  output logic [WIDTH - 1:0] q_oA,
  output logic [WIDTH - 1:0] q_oB,
  output logic [WIDTH - 1:0] q_oC,
  output logic overflow_oA,
  output logic overflow_oB,
  output logic overflow_oC,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
wor i_countertmrErrorC;
wor i_countertmrErrorB;
wor i_countertmrErrorA;

delta_counterTMR i_counter (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .clear_iA(clear_iA),
    .clear_iB(clear_iB),
    .clear_iC(clear_iC),
    .en_iA(en_iA),
    .en_iB(en_iB),
    .en_iC(en_iC),
    .load_iA(load_iA),
    .load_iB(load_iB),
    .load_iC(load_iC),
    .down_iA(down_iA),
    .down_iB(down_iB),
    .down_iC(down_iC),
    .delta_iA({{ WIDTH - 1 {1'b0} } , 1'b1}),
    .delta_iB({{ WIDTH - 1 {1'b0} } , 1'b1}),
    .delta_iC({{ WIDTH - 1 {1'b0} } , 1'b1}),
    .d_iA(d_iA),
    .d_iB(d_iB),
    .d_iC(d_iC),
    .q_oA(q_oA),
    .q_oB(q_oB),
    .q_oC(q_oC),
    .overflow_oA(overflow_oA),
    .overflow_oB(overflow_oB),
    .overflow_oC(overflow_oC),
    .tmrErrorA(i_countertmrErrorA),
    .tmrErrorB(i_countertmrErrorB),
    .tmrErrorC(i_countertmrErrorC)
  );
assign tmrErrorA = i_countertmrErrorA;
assign tmrErrorB = i_countertmrErrorB;
assign tmrErrorC = i_countertmrErrorC;
endmodule

