/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ./obi_uartTMR.sv                                                                       *
 *                                                                                                  *
 * user    : michaero                                                                               *
 * host    : camellia.ee.ethz.ch                                                                    *
 * date    : 08/08/2025 19:23:46                                                                    *
 *                                                                                                  *
 * workdir : /scratch/michaero/git/croc/working_dir/obi_peripherals/tmrg_files                      *
 * cmd     : /home/michaero/.local/bin/tmrg --inc-                                                  *
 *           dir=.bender/git/checkouts/common_cells-3510fb294b1f35a1/include ../tmrg_src/sync.sv    *
 *           ../tmrg_src/delta_counter.sv ../tmrg_src/counter.sv ../tmrg_src/fifo_v3.sv             *
 *           ../hw/obi_uart/obi_uart_pkg.sv ../hw/obi_uart/obi_uart_baudgen.sv                      *
 *           ../hw/obi_uart/obi_uart_interrupts.sv ../hw/obi_uart/obi_uart_modem.sv                 *
 *           ../hw/obi_uart/obi_uart_rx.sv ../hw/obi_uart/obi_uart_tx.sv                            *
 *           ../hw/obi_uart/obi_uart_register.sv ../hw/obi_uart/obi_uart.sv --top-module=delta_counter *
 * tmrg rev: 7e2935137fada05d9957c7acbad06f9f466f5f7e                                               *
 *                                                                                                  *
 * src file: ../hw/obi_uart/obi_uart.sv                                                             *
 *           Git SHA           : e6e399eed41c083c058e93c183edcf840d8a1f2a ( M ../hw/obi_uart/obi_uart.sv) *
 *           Modification time : 2025-08-08 19:23:40.280589                                         *
 *           File Size         : 6535                                                               *
 *           MD5 hash          : c0881c24078e0ce720b90667f48bb2eb                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module obi_uartTMR (
  input logic clk_i,
  input logic rst_ni,
  input obi_req_t obi_req_iA,
  input obi_req_t obi_req_iB,
  input obi_req_t obi_req_iC,
  output obi_rsp_t obi_rsp_oA,
  output obi_rsp_t obi_rsp_oB,
  output obi_rsp_t obi_rsp_oC,
  output logic irq_oA,
  output logic irq_oB,
  output logic irq_oC,
  output logic irq_noA,
  output logic irq_noB,
  output logic irq_noC,
  input logic rxd_i,
  output logic txd_o,
  input logic cts_ni,
  input logic dsr_ni,
  input logic ri_ni,
  input logic cd_ni,
  output logic rts_no,
  output logic dtr_no,
  output logic out1_no,
  output logic out2_no,
  output tmrError,
  output tmrErrorA,
  output tmrErrorB,
  output tmrErrorC
);
import obi_uart_pkg::*;
wire rxd_iC;
wire rxd_iB;
wire rxd_iA;
wor i_uart_txtmrErrorC;
wor i_uart_rxtmrErrorC;
wor i_uart_registertmrErrorC;
wor i_uart_modemtmrErrorC;
wor i_uart_interruptstmrErrorC;
wor i_uart_baudgentmrErrorC;
wor i_uart_txtmrErrorB;
wor i_uart_rxtmrErrorB;
wor i_uart_registertmrErrorB;
wor i_uart_modemtmrErrorB;
wor i_uart_interruptstmrErrorB;
wor i_uart_baudgentmrErrorB;
wor i_uart_txtmrErrorA;
wor i_uart_rxtmrErrorA;
wor i_uart_registertmrErrorA;
wor i_uart_modemtmrErrorA;
wor i_uart_interruptstmrErrorA;
wor i_uart_baudgentmrErrorA;
wor txdTmrError;
wor reg_readTmrError;
wire txd;
wire reg_read_t reg_read;
logic rxdA;
logic rxdB;
logic rxdC;
logic txdA;
logic txdB;
logic txdC;
logic rx_fifo_triggerA;
logic rx_fifo_triggerB;
logic rx_fifo_triggerC;
logic rx_timeoutA;
logic rx_timeoutB;
logic rx_timeoutC;
reg_read_t reg_readA;
reg_read_t reg_readB;
reg_read_t reg_readC;
reg_write_t reg_writeA;
reg_write_t reg_writeB;
reg_write_t reg_writeC;
logic oversample_rate_edgeA;
logic oversample_rate_edgeB;
logic oversample_rate_edgeC;
logic double_rate_edgeA;
logic double_rate_edgeB;
logic double_rate_edgeC;
logic baud_rate_edgeA;
logic baud_rate_edgeB;
logic baud_rate_edgeC;

obi_uart_registerTMR #(.obi_req_t(obi_req_t), .obi_rsp_t(obi_rsp_t)) i_uart_register (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .obi_req_iA(obi_req_iA),
    .obi_req_iB(obi_req_iB),
    .obi_req_iC(obi_req_iC),
    .obi_rsp_oA(obi_rsp_oA),
    .obi_rsp_oB(obi_rsp_oB),
    .obi_rsp_oC(obi_rsp_oC),
    .reg_read_oA(reg_readA),
    .reg_read_oB(reg_readB),
    .reg_read_oC(reg_readC),
    .reg_write_iA(reg_writeA),
    .reg_write_iB(reg_writeB),
    .reg_write_iC(reg_writeC),
    .tmrErrorA(i_uart_registertmrErrorA),
    .tmrErrorB(i_uart_registertmrErrorB),
    .tmrErrorC(i_uart_registertmrErrorC)
  );

obi_uart_modemTMR i_uart_modem (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .cts_ni(cts_ni),
    .dsr_ni(dsr_ni),
    .ri_ni(ri_ni),
    .cd_ni(cd_ni),
    .rts_no(rts_no),
    .dtr_no(dtr_no),
    .out1_no(out1_no),
    .out2_no(out2_no),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .reg_write_oA(reg_writeA.modem),
    .reg_write_oB(reg_writeB.modem),
    .reg_write_oC(reg_writeC.modem),
    .tmrErrorA(i_uart_modemtmrErrorA),
    .tmrErrorB(i_uart_modemtmrErrorB),
    .tmrErrorC(i_uart_modemtmrErrorC)
  );
assign txd_o = (reg_read.mcr.loopback==1'b1) ? 1'b1 : txd;
assign rxdA = (reg_readA.mcr.loopback==1'b1) ? txdA : rxd_iA;
assign rxdB = (reg_readB.mcr.loopback==1'b1) ? txdB : rxd_iB;
assign rxdC = (reg_readC.mcr.loopback==1'b1) ? txdC : rxd_iC;

obi_uart_baudgenTMR i_uart_baudgen (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oversample_rate_edge_oA(oversample_rate_edgeA),
    .oversample_rate_edge_oB(oversample_rate_edgeB),
    .oversample_rate_edge_oC(oversample_rate_edgeC),
    .double_rate_edge_oA(double_rate_edgeA),
    .double_rate_edge_oB(double_rate_edgeB),
    .double_rate_edge_oC(double_rate_edgeC),
    .baud_rate_edge_oA(baud_rate_edgeA),
    .baud_rate_edge_oB(baud_rate_edgeB),
    .baud_rate_edge_oC(baud_rate_edgeC),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .tmrErrorA(i_uart_baudgentmrErrorA),
    .tmrErrorB(i_uart_baudgentmrErrorB),
    .tmrErrorC(i_uart_baudgentmrErrorC)
  );

obi_uart_rxTMR i_uart_rx (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oversample_rate_edge_iA(oversample_rate_edgeA),
    .oversample_rate_edge_iB(oversample_rate_edgeB),
    .oversample_rate_edge_iC(oversample_rate_edgeC),
    .baud_rate_edge_iA(baud_rate_edgeA),
    .baud_rate_edge_iB(baud_rate_edgeB),
    .baud_rate_edge_iC(baud_rate_edgeC),
    .rxd_iA(rxdA),
    .rxd_iB(rxdB),
    .rxd_iC(rxdC),
    .trigger_oA(rx_fifo_triggerA),
    .trigger_oB(rx_fifo_triggerB),
    .trigger_oC(rx_fifo_triggerC),
    .timeout_oA(rx_timeoutA),
    .timeout_oB(rx_timeoutB),
    .timeout_oC(rx_timeoutC),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .reg_write_oA(reg_writeA.rx),
    .reg_write_oB(reg_writeB.rx),
    .reg_write_oC(reg_writeC.rx),
    .tmrErrorA(i_uart_rxtmrErrorA),
    .tmrErrorB(i_uart_rxtmrErrorB),
    .tmrErrorC(i_uart_rxtmrErrorC)
  );

obi_uart_txTMR i_uart_tx (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .baud_rate_edge_iA(baud_rate_edgeA),
    .baud_rate_edge_iB(baud_rate_edgeB),
    .baud_rate_edge_iC(baud_rate_edgeC),
    .double_rate_edge_iA(double_rate_edgeA),
    .double_rate_edge_iB(double_rate_edgeB),
    .double_rate_edge_iC(double_rate_edgeC),
    .txd_oA(txdA),
    .txd_oB(txdB),
    .txd_oC(txdC),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .reg_write_oA(reg_writeA.tx),
    .reg_write_oB(reg_writeB.tx),
    .reg_write_oC(reg_writeC.tx),
    .tmrErrorA(i_uart_txtmrErrorA),
    .tmrErrorB(i_uart_txtmrErrorB),
    .tmrErrorC(i_uart_txtmrErrorC)
  );

obi_uart_interruptsTMR i_uart_interrupts (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .rx_fifo_triggerA(rx_fifo_triggerA),
    .rx_fifo_triggerB(rx_fifo_triggerB),
    .rx_fifo_triggerC(rx_fifo_triggerC),
    .rx_timeoutA(rx_timeoutA),
    .rx_timeoutB(rx_timeoutB),
    .rx_timeoutC(rx_timeoutC),
    .irq_oA(irq_oA),
    .irq_oB(irq_oB),
    .irq_oC(irq_oC),
    .irq_noA(irq_noA),
    .irq_noB(irq_noB),
    .irq_noC(irq_noC),
    .reg_read_iA(reg_readA),
    .reg_read_iB(reg_readB),
    .reg_read_iC(reg_readC),
    .reg_write_iA(reg_writeA),
    .reg_write_iB(reg_writeB),
    .reg_write_iC(reg_writeC),
    .reg_isr_oA(reg_writeA.isr),
    .reg_isr_oB(reg_writeB.isr),
    .reg_isr_oC(reg_writeC.isr),
    .tmrErrorA(i_uart_interruptstmrErrorA),
    .tmrErrorB(i_uart_interruptstmrErrorB),
    .tmrErrorC(i_uart_interruptstmrErrorC)
  );

majorityVoter #(.WIDTH(70)) reg_readVoter (
    .inA(reg_readA),
    .inB(reg_readB),
    .inC(reg_readC),
    .out(reg_read),
    .tmrErr(reg_readTmrError)
  );

majorityVoter txdVoter (
    .inA(txdA),
    .inB(txdB),
    .inC(txdC),
    .out(txd),
    .tmrErr(txdTmrError)
  );
assign tmrError = reg_readTmrError|txdTmrError;
assign tmrErrorA = i_uart_baudgentmrErrorA|i_uart_interruptstmrErrorA|i_uart_modemtmrErrorA|i_uart_registertmrErrorA|i_uart_rxtmrErrorA|i_uart_txtmrErrorA;
assign tmrErrorB = i_uart_baudgentmrErrorB|i_uart_interruptstmrErrorB|i_uart_modemtmrErrorB|i_uart_registertmrErrorB|i_uart_rxtmrErrorB|i_uart_txtmrErrorB;
assign tmrErrorC = i_uart_baudgentmrErrorC|i_uart_interruptstmrErrorC|i_uart_modemtmrErrorC|i_uart_registertmrErrorC|i_uart_rxtmrErrorC|i_uart_txtmrErrorC;

fanout rxd_iFanout (
    .in(rxd_i),
    .outA(rxd_iA),
    .outB(rxd_iB),
    .outC(rxd_iC)
  );
endmodule



// /scratch/michaero/git/tmrg/tmrg/../common/voter.v
module majorityVoter #(
  parameter WIDTH = 1
)(
  input wire  [WIDTH-1:0] inA,
  input wire  [WIDTH-1:0] inB,
  input wire  [WIDTH-1:0] inC,
  output wire [WIDTH-1:0] out,
  output reg              tmrErr
);
  assign out = (inA&inB) | (inA&inC) | (inB&inC);
  always @(inA or inB or inC) begin
    if (inA!=inB || inA!=inC || inB!=inC)
      tmrErr = 1;
    else
      tmrErr = 0;
  end
endmodule


// /scratch/michaero/git/tmrg/tmrg/../common/fanout.v
module fanout #(
  parameter WIDTH = 1
)(
  input wire  [WIDTH-1:0] in,
  output wire [WIDTH-1:0] outA,
  output wire [WIDTH-1:0] outB,
  output wire [WIDTH-1:0] outC
);
  assign outA = in;
  assign outB = in;
  assign outC = in;
endmodule
