/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ./syncTMR.sv                                                                           *
 *                                                                                                  *
 * user    : michaero                                                                               *
 * host    : camellia.ee.ethz.ch                                                                    *
 * date    : 08/08/2025 19:23:44                                                                    *
 *                                                                                                  *
 * workdir : /scratch/michaero/git/croc/working_dir/obi_peripherals/tmrg_files                      *
 * cmd     : /home/michaero/.local/bin/tmrg --inc-                                                  *
 *           dir=.bender/git/checkouts/common_cells-3510fb294b1f35a1/include ../tmrg_src/sync.sv    *
 *           ../tmrg_src/delta_counter.sv ../tmrg_src/counter.sv ../tmrg_src/fifo_v3.sv             *
 *           ../hw/obi_uart/obi_uart_pkg.sv ../hw/obi_uart/obi_uart_baudgen.sv                      *
 *           ../hw/obi_uart/obi_uart_interrupts.sv ../hw/obi_uart/obi_uart_modem.sv                 *
 *           ../hw/obi_uart/obi_uart_rx.sv ../hw/obi_uart/obi_uart_tx.sv                            *
 *           ../hw/obi_uart/obi_uart_register.sv ../hw/obi_uart/obi_uart.sv --top-module=delta_counter *
 * tmrg rev: 7e2935137fada05d9957c7acbad06f9f466f5f7e                                               *
 *                                                                                                  *
 * src file: ../tmrg_src/sync.sv                                                                    *
 *           Git SHA           : e6e399eed41c083c058e93c183edcf840d8a1f2a (?? ../tmrg_src/sync.sv)  *
 *           Modification time : 2025-08-08 18:55:28.649228                                         *
 *           File Size         : 1440                                                               *
 *           MD5 hash          : ac894a6fb7b557ad081ef7878e92f700                                   *
 *                                                                                                  *
 ****************************************************************************************************/

module syncTMR #(
  parameter int unsigned STAGES = 2,
  parameter bit ResetValue = 1'b0
) (
  input logic clk_i,
  input logic rst_ni,
  input logic serial_iA,
  input logic serial_iB,
  input logic serial_iC,
  output logic serial_oA,
  output logic serial_oB,
  output logic serial_oC
);
wire rst_niC;
wire rst_niB;
wire rst_niA;
wire clk_iC;
wire clk_iB;
wire clk_iA;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] reg_qA;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] reg_qB;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] reg_qC;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] sync_qVotedA;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] sync_qVotedB;
(* dont_touch = "true" *)(* async_reg = "true" *) logic [STAGES - 1:0] sync_qVotedC;
assign sync_qVotedA = reg_qA;
assign sync_qVotedB = reg_qB;
assign sync_qVotedC = reg_qC;

always_ff @( posedge clk_iA or negedge rst_niA )
  begin
    if (!rst_niA)
      begin
        reg_qA <= {STAGES{ResetValue}};
      end
    else
      begin
        reg_qA <= {sync_qVotedA[STAGES - 2:0], serial_iA};
      end
  end

always_ff @( posedge clk_iB or negedge rst_niB )
  begin
    if (!rst_niB)
      begin
        reg_qB <= {STAGES{ResetValue}};
      end
    else
      begin
        reg_qB <= {sync_qVotedB[STAGES - 2:0], serial_iB};
      end
  end

always_ff @( posedge clk_iC or negedge rst_niC )
  begin
    if (!rst_niC)
      begin
        reg_qC <= {STAGES{ResetValue}};
      end
    else
      begin
        reg_qC <= {sync_qVotedC[STAGES - 2:0], serial_iC};
      end
  end
assign serial_oA = reg_qVoted[STAGES-1];
assign serial_oB = reg_qVoted[STAGES-1];
assign serial_oC = reg_qVoted[STAGES-1];

fanout clk_iFanout (
    .in(clk_i),
    .outA(clk_iA),
    .outB(clk_iB),
    .outC(clk_iC)
  );

fanout rst_niFanout (
    .in(rst_ni),
    .outA(rst_niA),
    .outB(rst_niB),
    .outC(rst_niC)
  );
endmodule

