# Copyright 2026 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

services:
  eda-tools:
    image: hpretl/iic-osic-tools:2025.12
    environment:
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"
    volumes:
      - ./:/workspace/obi_peripherals
    stdin_open: true
    tty: true
    working_dir: /workspace/obi_peripherals
    entrypoint: /dockerstartup/scripts/ui_startup.sh
    command: --skip bash
